// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.core.math.rect;


import std.traits : isNumeric;
import inmath.linalg : Rect;
public import inmath.linalg : rect, rectd;

alias recti = Rect!int;