// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.vfs.disk.loader;


import std.path : baseName;
import std.file : exists, isDir;
import zyeware;
import zyeware.vfs.disk.dir : VfsDiskDirectory;

package(zyeware.vfs):

/// Loads file system directories as Vfs directories.
class VfsDiskLoader : VfsLoader {

public:

VfsDirectory load(string diskPath, string scheme) const;

bool eligable(string diskPath) const;
}