// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.rendering.cursor;


import std.conv : to;
import zyeware;

@asset(Yes.cache) final class Cursor {

protected:

const Image mImage;

vec2i mHotspot;

public:

this(const Image image, vec2i hotspot) {
mImage = image;
mHotspot = hotspot;
}

const(Image) image() pure const nothrow;

vec2i hotspot() pure const nothrow;

static Cursor load(string path);
}