// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.rendering.texatlas;


import zyeware;

struct TextureAtlas {

private:

Texture2d mTexture;

size_t mHFrames, mVFrames;

public:

this(Texture2d texture, size_t hFrames, size_t vFrames) pure nothrow {
mTexture = texture;
mHFrames = hFrames;
mVFrames = vFrames;
}

rect getRegionForFrame(size_t frame) pure const nothrow;

vec2 spriteSize() pure const nothrow;

inout(Texture2d) texture() pure inout nothrow;
}