// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.rendering.vertex;


import zyeware;

struct Vertex2D {

vec2 position;

vec2 uv;

color modulate;
}

struct Vertex3D {

vec3 position;

vec3 normal;

vec2 uv;

color modulate;
}