// This file was generated by ZyeWare APIgen. Do not edit!
module zyeware.vfs.utils;


import std.string : indexOf, lastIndexOf;
import std.array : Appender;

string getScheme(string path) pure;

string stripScheme(string path) pure;

string getExtension(string path) pure;

string stripExtension(string path) pure;

string getBasename(string path) pure;

string getDirname(string path) pure;

string buildPath(string[] paths...) pure nothrow;